export const LoginTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CHANGE_EMAIL_LOGIN: "CHANGE_EMAIL_LOGIN",
    CHANGE_PASSWORD_LOGIN: "CHANGE_PASSWORD_LOGIN",
    ISFETCHING_LOGIN_START: "ISFETCHING_LOGIN_START",
    ISFETCHING_LOGIN_COMPLETE: "ISFETCHING_LOGIN_COMPLETE"

}