export const EmpleadosTypes = {
    GET_EMPLEADOS_COMPLETE: "GET_EMPLEADOS_COMPLETE",
    ISFETCHING_START: "ISFETCHING_START",
    ISFETCHING_COMPLETE: "ISFETCHING_COMPLETE",
    CHANGE_NOMBRE: "CHANGE_NOMBRE",
    CHANGE_EMAIL: "CHANGE_EMAIL",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    CHANGE_ADMIN: "CHANGE_ADMIN",
    CARGA_FORM_ALTA: "CARGA_FORM_ALTA",
    CARGA_FORM_MODIFICA: "CARGA_FORM_MODIFICA"
};