export const TiposJornadaTypes = {
    GET_TIPOSJORNADA_COMPLETE: "GET_TIPOSJORNADA_COMPLETE",
    ISFETCHING_START: "ISFETCHING_START",
    ISFETCHING_COMPLETE: "ISFETCHING_COMPLETE",
    CHANGE_TIPO: "CHANGE_TIPO",
    CARGA_FORM_ALTA: "CARGA_FORM_ALTA",
};