export const TurnosTypes = {
    // En este archivo se guardan los tipos de acciones.
    CARGA_FORM_TURNOS: "CARGA_FORM_TURNOS",
    GET_TURNOS_COMPLETE: "GET_TURNOS_COMPLETE",
    ISFETCHING_START: "ISFETCHING_START",
    ISFETCHING_COMPLETE: "ISFETCHING_COMPLETE",
    CHANGE_DIA: "CHANGE_DIA",
    CHANGE_MES: "CHANGE_MES",
    CHANGE_ANIO: "CHANGE_ANIO",
    CHANGE_EMPLEADO: "CHANGE_EMPLEADO",
    CHANGE_HORARIO: "CHANGE_HORARIO",
    CHANGE_TIPO: "CHANGE_TIPO",
    TURNO_PERMITIDO: "TURNO_PERMITIDO"
};